### Update an existing patient Entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Mouhamed Baba Lamotte",
  "address": "Mariste",
  "email": "mouhamedlamotte.dev@gmail.com",
  "dateOfBirth": "2004-09-09"
}
###